#Property to change server port
server:
  port: 8082
  
#Database properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vaccinationCenterDB
    username: root
    password: India@11

#Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format-sql: true

#Properties to configure Eureka
  application:
    name: VACCINATION-CENTER-SERVICE
       
#Design Patterns used ONE Database for each SERVICE